hashgraph/pbj

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
changed >= and < to  `&gt;= 0 and &lt;` to get rid of build error in javadoc.
**Checklist**
> fixed build error

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingDataTest.java
Fix off-by-one error caused by `ReadableStreamingData` preloading a byte. If you use an input stream, and pass it to a `ReadableStreamingData`, and then read with the streaming data, and then create a new `ReadableStreamingData` with the same stream, the second one will be missing one byte. The fix is to require the InputStream passed to `ReadableStreamingData` to support `markSupported`. If it does, then we can make this work. Not sure on performance. Might need another pass later.
> Fix off-by-one on ReadableStreamingData due to preloading of a byte

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Common.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java
Due to the fact that the compiler expect a path separator to be `/`,  PBJ gradle task fails on Windows.
> Replaced `/` with OS-dependent path separator

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/RandomAccessData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/BytesTest.java
If the data is EMPTY, the contains throws OutOfBoundsException. Add a special code to deal with EMPTY buffers.
Fixes #
**Checklist**
> Fix for issue 37

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/ReadableSequentialData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingDataTest.java
In case of EOF readBytes() doesn't throw anymore, but returns the bytes read.
Fixes #
**Checklist**
> Make readBytes honor the contract of the Java libraries.

- pbj-core/pbj-compiler/build.gradle.kts
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Common.java
- pbj-core/pbj-compiler/src/test/java/com/hedera/pbj/compiler/impl/CommonTest.java
Added an extra line to remove the /** from the beginning of the original JavaDoc comment.
Fixes #
**Checklist**
> Removing of ** from original JavaDoc comments.

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java
Replaced `/` with OS-dependent path separator in the importedFileName to make sure that there is a match. This makes it work on Windows
> Replaced `/` with OS-dependent path separator in the importedFileName to make sure that there is a match.

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java
- pbj-core/pbj-compiler/src/test/java/com/hedera/pbj/compiler/impl/LookupHelperTest.java
Fixed issue with `replaceAll` that ignores backslashes.
> Fixed issue with `replaceAll` that ignores backslashes.

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/ReadableSequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedSequentialData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BufferedDataTest.java
A follow-up fix for https://github.com/hashgraph/pbj/issues/83. In complex `BufferedData` methods like `readVarInt()` or `readVarLong()`, which are more than just propagate to the underlying buffer, reading takes array offset (for sliced buffers) into consideration after the fix above. However, when position is updated to skip the bytes read, the offset is still ignored. This PR changes that.
A couple new unit tests are provided.
Fixes: https://github.com/hashgraph/pbj/issues/90
> 90: BufferedData slices are still broken

- pbj-core/pbj-compiler/src/main/antlr/com/hedera/hashgraph/protoparser/grammar/Protobuf3.g4
- pbj-integration-tests/src/main/proto/timestampTest.proto
Couple of fixes to the grammar.
Made a couple of changes in the grammar to fix issues. Allowed DOC_COMMENTS on top level of the file.
The issue here was not an error, but a warning. The runtime was still working properly.
Fixes #87
> Fix issue 87.

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/ReadableSequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/RandomAccessData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BufferedDataTest.java
Fix for leaking reference into read Bytes object, it must be a copy to be safe because Bytes is expected to be immutable.
Also fixed toString hex printing.
> 104 no pass though

- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.conventions.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.gradle-plugin.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.runtime.gradle.kts
This pull request changes the following:
- Fixes Gradle plugin portal publishing
- Fixes Maven Central publishes
- Related to #92 
- Closes #112
> fix: configuration issues preventing proper publishing of Maven Central and Gradle plugin artifacts

- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.conventions.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.maven-publish.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.runtime.gradle.kts
While the signing for Gradle plugins published to the Plugin Portal is automatically done (through `com.gradle.plugin-publish`), it needs to be explicitly defined for publishing to "normal" maven repositories like central.
This PR adds this back (was accidentally removed in #92).
This PR also partially reverts #113 so that all publishing configuration that should be used for **both** Plugin Portal and Maven Central is kept in `com.hedera.pbj.maven-publish.gradle.kts` and used by all projects. This concerns the informal metadata for POM files and the general signing setup.
> fix: sign when publishing to central / metadata for all publications

- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.root.gradle.kts
Reverted removal of `id("com.hedera.pbj.aggregate-reports")`
Related to #109
> Reverted removal of `id("com.hedera.pbj.aggregate-reports")`

- pbj-core/gradle.properties
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Common.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
Fix summary:
* A separate hashCode() generation branch for single-field messages is removed. Now hashCode() for all messages is generated using `Common.getFieldsHashCode()`
* Minor formatting changes
Fixes: https://github.com/hashgraph/pbj/issues/119
> 119: Generated hashCode() implementation does not compile

- pbj-core/pbj-runtime/src/jmh/java/com/hedera/pbj/runtime/io/BufferedDataGetBytes.java
- pbj-core/pbj-runtime/src/jmh/java/com/hedera/pbj/runtime/io/ByteBufferGetByte.java
- pbj-core/pbj-runtime/src/jmh/java/com/hedera/pbj/runtime/io/ByteBufferGetBytes.java
- pbj-core/pbj-runtime/src/jmh/java/com/hedera/pbj/runtime/io/ByteOrderEquals.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/UnsafeUtils.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/ByteArrayBufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/DirectBufferedData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BufferedDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BufferedDataTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BufferedTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/ByteArrayBufferedDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BytesTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/DirectBufferedDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/RandomAccessTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/StubbedRandomAccessDataTest.java
Fix summary:
* Two subclasses of `BufferedData` are provided: `ByteArrayBufferedData` and `DirectBufferedData`
* Byte array version uses `System.arraycopy()` to get / read / write bytes
* Direct version uses `UnsafeUtils` methods to get / read / write bytes
* A new BufferedData level JMH benchmark is provided
* New unit tests are provided for the two new subclasses
* A couple unit tests which were specific to `Bytes` are made generic, so they are applicable to other random access data implementations, including `BufferedData` and its subclasses
Fixes: https://github.com/hashgraph/pbj/issues/60
> 60: Improve BufferedData Performance

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-integration-tests/settings.gradle.kts
Without this fix, when an empty protobuf definition is supplied, the generator and tests fail.
Fixes #130
Add an empty protobuf message to the hedera-protobufs repo, or change settings.gradle.kts to use
uri.set("https://github.com/nickpoorman/hedera-protobufs.git")
// choose tag or branch of HAPI you would like to test with
tag.set("block-node")
and run the build task on pbj-integration-tests.
See it done here: https://github.com/hashgraph/pbj/commit/5091ab928b0c92a6260bd4b5ed8e91ca7d7a836f#diff-33c26aa8d64828ee0a21e949f86378b4702433336009b2a6575795e6416d7d29R26
**Checklist**
> fix: properly generate code and pass tests when protobuf message definition is empty

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/ByteArrayBufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/WritableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableSequentialDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableSequentialTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/WritableSequentialDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/WritableTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BufferedDataTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/WritableStreamingDataTest.java
Fix summary:
* `readBytes()` methods are implemented in `ReadableStreamingData` in a more efficient way than inherited from `ReadableSequentialData`
* Unit tests are refactored, so some tests previously run for `ReadableStreamingData` only now are also used for other implementations of `ReadableSequentialData` (e.g. `BufferedData`)
Fixes: https://github.com/hashgraph/pbj/issues/27
> fix: 27: ReadableStreamingData should implement bulk read methods

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/WritableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/WritableStreamingDataTest.java
Replacing AutoCloseable with Closeable in ReadableStreamingData and WritableStreamingData classes and updating a unit test for the latter to use IOException instead of plain Exception.
Fixes #134
```
pbj-core]$ ./gradlew test
...
BUILD SUCCESSFUL in 10s
```
**Checklist**
- [x ] Documented (Code comments, README, etc.)
- [x ] Tested (unit, integration, etc.)
> fix 134: replace AutoCloseable with Closeable

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingDataTest.java
Fix summary:
* A new constructor is added to `ReadableStreamingData` to create a streaming object for a file path. It opens a new file input stream and sets the limit to the size of the file
* A new constructor is added to the same class to create a streaming object from a byte array. It creates a ByteArrayInputStream, the limit is set to byte array length
Testing:
* New unit tests are added to cover both new constructors and check the limits
Fixes: https://github.com/hashgraph/pbj/issues/110
> fix: 110: ReadableStreamingData limit is not set if it's wrapped over a file stream

- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/FuzzTestException.java
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTest.java
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTestResult.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/SampleFuzzTest.java
Introducing the `SingleFuzzTest` class to support fuzz testing.
This is the first in a series of pull requests that will ultimately build a framework to run fuzz testing for pbj.
Here I'm introducing a new utility class that can perform a single randomized run of a fuzz test and return a result value that indicates whether the test was successful or more testing may be needed. See javadocs for more details.
Please note that building the entire fuzz testing framework is outside of scope of this particular PR and will be done in future, separate PRs.
Fixes #68 
```
pbj-integration-tests]$ ./gradlew test --info
...
STANDARD_OUT
SingleFuzzTest 0: Object: AccountID[shardNum=3, realmNum=2, account=OneOf[kind=ACCOUNT_NUM, value=1]] …
```
> fix 68: introduce SingleFuzzTest

- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/FuzzTest.java
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/FuzzTestResult.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/SampleFuzzTest.java
Introducing a FuzzTest class that allows one to run a comprehensive fuzz test for a given object and its codec. The class uses the `SingleFuzzTest.fuzzTest` to run the actual tests and then collects all the results in a statistics map with keys being the SingleFuzzTestResult enum constants, and values describing the percentage of that particular outcome occurring during the test.
A provided threshold is used to measure the `SingleFuzzTestResult.DESERIALIZATION_FAILED` outcome specifically as it's the most desired outcome of all.
The SampleFuzzTest.java has been modified to use the FuzzTest, and it finally can assert something real and useful.
In future PR the SampleFuzzTest will be replaced with something that would be testing all the object models that pbj currently …
> fix 68: introduce FuzzTest

- pbj-core/pbj-runtime/src/jmh/java/com/hedera/pbj/runtime/io/ByteBufferGetByte.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/ReadableSequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/UnsafeUtils.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/WritableSequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/ByteArrayBufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/DirectBufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/RandomAccessData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/DataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/WritableTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/RandomAccessTestBase.java
- pbj-integration-tests/src/jmh/java/com/hedera/pbj/intergration/jmh/VarIntBench.java
Fix summary:
* Fixed `VarIntBench` JMH benchmark
* Improved `getVarInt/Long()` and `readVarIntLong()` implementations for all applicable classes
* Added several new unit tests
* Refactored some existing tests, so they are run for more classes
* Renamed a few `UnsafeUtils` methods and added methods without range checks
Fixes: https://github.com/hashgraph/pbj/issues/67
Fixes: https://github.com/hashgraph/pbj/issues/143
> fix: 67: Compare & Improve General Protobuf performance

- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/FuzzTest.java
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/FuzzTestException.java
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/FuzzTestResult.java
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTest.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/SampleFuzzTest.java
This is a re-send of https://github.com/hashgraph/pbj/pull/146 because that branch got broken.
1. Using the already existing ModelTest.ARGUMENTS lists to fetch sample model objects for fuzz testing.
2. Modifying the SingleFuzzTest to inflict more damage to the message payload, so as to increase the probability of the codec failing. W/o this change the threshold of 50% wasn't always enough.
3. Extend the SampleFuzzTest to support both the old AccountID and the new ContractID models.
4. Minor changes in other related places.
Please note that it is still OUT OF SCOPE of this PR to extend support to all the models supported by pbj. There's already a lot of code in this single change that I'd like to push separately.
We'll be adding support for testing all the models in …
> fix 68: use ModelTest.ARGUMENTS and extend SampleFuzzTest to ContractID

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/ReadableSequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingDataTest.java
> fix: 151 Fixed incorrect `readVarLong` behavior in case of prematurely ended stream in `ReadableStreamingData`

- pbj-integration-tests/build.gradle.kts
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/FuzzTest.java
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTest.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/SampleFuzzTest.java
1. Adding about 8 more test models to run the fuzz test against. The total number of test objects from their `ARGUMENTS` is a little over 300.
2. Splitting the `integTest` and `fuzzTest` Gradle targets to run the fuzz tests with assertions off, and making the regular `test` target depend on both.
3. Minor adjustments to heuristics used in the fuzz test.
Please note that the `THRESHOLD` mechanism will be overhauled in a future PR where I'll replace the individual tests failures with gathering of statistics across all runs, and then deciding if the test as a whole should fail or not. But this is OUTSIDE OF SCOPE of this particular PR.
Fixes #68 
1. The output of the test is similar as before but it now tests against more than …
> fix 68: extend fuzz test to more models

- pbj-integration-tests/build.gradle.kts
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/FuzzTest.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/SampleFuzzTest.java
1. By default, the `fuzzTest` will use a constant seed for a single Random object used for all the fuzz tests. And these tests now run sequentially. This will ensure that the tests don't fail randomly. And this also allows us to reproduce the failures if they occur.
2. A new `randomFuzzTest` Gradle target is added to enable running the tests with a random seed for discovering new issues. This new target must be run manually if/when desired.
3. The threshold values and their application to the results of the tests has been totally overhauled. The test now gathers all the results and computes statistics over the individual pass/failure statuses as well as the individual `DESERIALIZATION_FAILED` rates. We pass or fail the fuzz test as a whole if the pass rate across all the …
> fix 68: fix the Random seed and overhaul thresholds

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Codec.java
Fix summary: two default methods are added to `Codec` interface to parse / parseStrict from a `Bytes` object.
Fixes: https://github.com/hashgraph/pbj/issues/72
> fix: 72: Add convenience parse method to Codec for parsing Bytes

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/MalformedProtobufException.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/SequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/RandomAccessSequenceAdapter.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/WritableStreamingData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/test/CharBufferToWritableSequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/test/Sneaky.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/test/UncheckedThrowingFunction.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoParserToolsTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableSequentialDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableSequentialTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/SequentialTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/WritableSequentialDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/WritableTestBase.java
Addressing a few parsing issues that led to discrepancies between Google Protobuf behavior and PBJ's. Specifically:
1. Re-implementing https://github.com/hashgraph/pbj/pull/47 to reduce the scope of the try/catch block that swallows EOFException to only do that at the beginning of reading a field. When this exception is thrown anywhere else during the parsing of the field, then the parser errors out too.
2. Adding length/position checks to the repeated fields parser.
3. Modifying the string parser to error out on invalid UTF-8 data.
4. Modifying the delimited field skipper to error out on negative length.
5. Modifying the skip() implementation to error out if there's not enough bytes remaining in the buffer to skip.
Also introducing a couple of helper classes - `Sneaky` …
> fix 68: improve parsing

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-integration-tests/src/main/proto/bytes.proto
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/BytesNonNullTest.java
* Annotate `bytes` fields with `@NonNull`.
* Modify the builder to also use the annotation for `bytes` fields, as well as substitute `null` values passed to the builder with their default values.
* Added a test to verify this behavior.
Fixes #106 
All tests (including the new one) in all of pbj-runtime/compiler/integ tests pass.
**Checklist**
> fix 106: bytes should never be null

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Codec.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/RandomAccessSequenceAdapter.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BytesTest.java
- pbj-integration-tests/src/main/proto/bytes.proto
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/ParserNeverWrapsTest.java
Problem statement: in PBJ, parsing a model from a data buffer should create copies of data, especially for byte arrays, rather than use a direct view to the original buffer. Note that strings are covered for us by JDK itself because it always creates a copy. So of all the primitive types that we support in PBJ, only byte arrays need to be taken care of.
In this fix, the Codec.parse(Bytes) replaces usages of `Bytes.toReadableSequentialData` with a new `Bytes.toCopyingReadableSequentialData`. The latter initializes a returned `RandomAccessSequenceAdapter` object with a special flag that makes its `Bytes readBytes(int length)` method create a copy of the returned bytes.
Also, a test is added that checks all the three non-test implementations of the ReadableSequentialData on …
> fix 104: Parsing should never wrap

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java
Fix summary:
* New methods are added to `ProtoWriterTools` to write repeated fields one by one (in contrast to `writeXYZList()`, which expects all repeated values are passed as a list): `writeOneRepeatedBytes()`, `writeOneRepeatedMessage()`, and `writeOneRepeatedString()`
* These methods are identical to the corresponding `writeXYZ()`, except the assertion about field repeated type is opposite
* New tests are provided for the new methods. They check that the new methods, if called multiple times, are identical to the corresponding `writeXYZList()`
Fixes: https://github.com/hashgraph/pbj/issues/76
> fix: 76: Need API to write repeated bytes fields one message by one

- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.spotless-java-conventions.gradle.kts
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/PbjCompilerTask.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-integration-tests/src/main/proto/comparable.proto
* Adjusted ModelGenerator to use field `name` instead of `nameCamelFirstLower` when filtering comparable fields.
* Added an abbreviated stack trace for exceptions when compiling proto files, to help debug future issues like this.
* Modified comparable.proto in integration tests, renaming `bytes bytes` to `bytes test_bytes` to prevent regression.
* Modified the spotless conventions to allow Java 21 to be used
Fixes: #175
> fix: 175 CompareTo Generation fails if fields include underscores

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java
* Making ProtoWriterTools.sizeOfUnsignedVarInt32() public
* Adding ProtoWriterTools.writeDelimited() which is a copy of ProtoUtils.writeDelimited() from hedera-services with an added javadoc.
Prerequisite for: https://github.com/hashgraph/hedera-services/issues/11030
Build passes.
**Checklist**
> fix 11030: add public utils

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/json/JsonCodecParseMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecFastEqualsMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecMeasureDataMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Codec.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/JsonCodec.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/JsonTools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ParseException.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/UncheckedParseException.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/MalformedMessageTest.java
The Codec.parse() methods will throw a checked ParseException when parsing fails. The `cause` throwable of the ParseException provides details on the nature of the failure.
Original description:
~~Catching any RuntimeExceptions thrown in the parsing loop and wrapping them in IOException. Parsing is related to I/O, so this wrapping makes sense. Introducing a new dedicated checked ParseException would require changes to the parsing method signatures, and to all the places that use it which is a lot. Since the code calling the parsing method catches the IOException already, this fix solves the problem statement.~~
Fixes #114
All tests pass.
**Checklist**
> fix 114: Wrap unchecked Exceptions in checked Exception

- pbj-integration-tests/src/jmh/java/com/hedera/pbj/intergration/jmh/JsonBench.java
- pbj-integration-tests/src/jmh/java/com/hedera/pbj/intergration/jmh/ProtobufObjectBench.java
Fixing compile-time errors in jmh after https://github.com/hashgraph/pbj/pull/172
The build failure: https://github.com/hashgraph/pbj/actions/runs/7618734592/job/20750476803
Fixes #114 
`g jmh` is able to compile the code
**Checklist**
> fix 114: fix jmh compilation

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/WritableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/WritableStreamingDataTest.java
* Implement Flushable in WritableStreamingData.
* Update version to 0.7.15
Fixes #183 
* A new unit test is added.
* `test` target in pbj-runtime passes.
**Checklist**
> fix 183: implement Flushable in WritableStreamingData

- .github/workflows/flow-deploy-release-artifact.yaml
- pbj-core/buildSrc/build.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.conventions.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.gradle-plugin.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.root.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.runtime.gradle.kts
- pbj-core/gradle/modules.properties
- pbj-core/pbj-compiler/build.gradle.kts
- pbj-core/pbj-runtime/build.gradle.kts
- pbj-core/settings.gradle.kts
This pull request changes the following:
- Adds support for Nexus based automatic releases.
- Renames the `release-maven-*` tasks to follow typical Gradle conventions.
- Updates several plugin versions.
- Adds explicit Java source and target compatibility flags. 
- Closes #185
> feat: add support for automatic Nexus plugin based releases

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
* Added a test in the catch block to rethrow ParseException rather than wrapping it in another ParseException
> fix: Fix double-wrap of `ParseExecption`

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/OneOf.java
- pbj-core/pbj-runtime/src/test/java/tests/OneOfTest.java
Objects.hash(Object...) implicitly creates an array to hold all the arguments passed in, which has a high memory foot-print.
I'm replacing this call with a manual computation of the hash code. ~~Note that the value computed by the Objects.hash() is slightly different from the explicit computation (probably because it uses a seed value, while this fix implicitly uses a seed of 0), so I had to update the unit test as well. However,~~ I think it's a good idea to keep the unit test in sync with the actual code, to account for any changes that JDK may implement in Objects.hash() in the future.
Fixes #156 
`gr test` passes in all the three PBJ repos.
**Checklist**
> fix: 156: optimize OneOf.hashCode()

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/SingleField.java
Replacing `enum.values()[0]` with `enum.fromProtobufOrdinal(0)` in generated Builder implementations.
Fixes #157 
`gr test` passes in all three PBJ repos.
**Checklist**
> fix: 157: optimize enum default value initialization

- pbj-core/gradle.properties
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Field.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ParseException.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java
This fix introduces a default limit of 21K on repeated/length-encoded field sizes. When the parser encounters a field with a greater size, it errors out with ParseException.
This is a quick solution for release 48.
In a future release, we'll extend the functionality as described at https://github.com/hashgraph/pbj/issues/209.
Fixes #208 
All unit tests and all integration tests, including the fuzzTest, pass in all three PBJ sub-projects.
**Checklist**
> fix: 208: limit max size

- pbj-core/gradle.properties
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/SingleField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/json/JsonCodecParseMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Codec.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/JsonCodec.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/JsonTools.java
- pbj-integration-tests/src/main/proto/message.proto
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/MaxDepthTest.java
The fix allows the parser to limit the depth of nested objects parsed from the input. The parser would throw a ParseException when the limit is reached.
To accomplish this, I'm pulling the previously private parseInternal() method to the public scope in the Codec interface. This has a few advantages:
1. Avoiding a conditional when parsing nested messages (and also avoiding an extra nested call) which should all improve the performance.
2. Avoiding having to introduce multiple versions of parse/parseStrict methods with different sets of arguments to support legacy usages and the new ones.
The public parse() method now includes an extra argument that specifies the maximum depth of nested messages allowed.
I'm bumping the PBJ version to 0.8.0 as this is a relatively drastic …
> fix: 212: limit max depth

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Field.java
Increasing the maximum field size from 21K to 2M.
Fixes #221
`gr test` passes in all the three PBJ sub-projects.
**Checklist**
> fix: 221: increase Field.DEFAULT_MAX_SIZE to 2M

- pbj-core/gradle.properties
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/SingleField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/json/JsonCodecParseMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Codec.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/JsonCodec.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/JsonTools.java
- pbj-integration-tests/src/main/proto/message.proto
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/MaxDepthTest.java
* `git cherry-pick -n a5c136d6653481e036291a17158004825bf05cbe`, i.e. a verbatim re-application of https://github.com/hashgraph/pbj/pull/219
* The only modification of the above commit is the PBJ version `s/0.8.0/0.8.1/` because 0.8.0 has already been released in the past.
* And also removing a single comment from a single line in `ModelGenerator.java` to address a comment from https://github.com/hashgraph/pbj/pull/224
Fixes #212 
All tests in all 3 PBJ sub-projects pass.
**Checklist**
> re-apply fix: 212: limit max depth

- pbj-core/gradle.properties
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Common.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/OneOf.java
- pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java
- pbj-core/pbj-runtime/src/test/java/tests/OneOfTest.java
Apparently, `Enum.hashCode()` delegates to `Object.hashCode()` which makes the hash code value different in different VMs/between runs.
This fix replaces direct usages of `Enum.hashCode()` with `Enum.name().hashCode()`. The latter is computed on a `String` value which is stable because it only depends on the actual characters of the strings (i.e. names of enum constants) which are always the same for a given enum, regardless of a VM instance.
Fixes #227 
* All tests in all three PBJ projects pass
* A new test for ComparableOneOf is added.
**Checklist**
> fix: stabilize hashCode() for Enums

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Common.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/OneOf.java
- pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java
- pbj-core/pbj-runtime/src/test/java/tests/OneOfTest.java
Modifying the original implementation at https://github.com/hashgraph/pbj/pull/228 by switching from using `Enum.name().hashCode()` to `Integer.hashCode(EnumWithProtoMetadata.protoOrdinal())`.
Fixes #227 
* All tests in all three PBJ sub-projects pass.
**Checklist**
> fix: stabilize hashCode() for Enums using proto ordinals

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BytesTest.java
closes https://github.com/hashgraph/hedera-services/issues/12331
> chore: add signature support to `Bytes`

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/FieldsNonNullTest.java
PBJ already defaults repeated fields to empty lists in the parser and the builder. This fix makes model constructors do the same, and generally makes the repeated fields non-nullable.
Fixes #238
* Unit test
* `gr test` at hedera-services in hedera-file-service-impl which uses the FeeSchedule which was the main testing model.
The generated FeeSchedule ctor:
```
public FeeSchedule(List<TransactionFeeSchedule> transactionFeeSchedule, TimestampSeconds expiryTime) {
this.transactionFeeSchedule = transactionFeeSchedule == null ? Collections.emptyList() : transactionFeeSchedule;
this.expiryTime = expiryTime;
}
```
The generated Builder convenience method:
```
public Builder transactionFeeSchedule(TransactionFeeSchedule ... values) { …
```
> feat: make repeated fields @NonNull and default to empty lists

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BytesTest.java
Take into account the `start`/`length` of a wrapped sub-array in Bytes.
Fixes #236 
The new (and existing) unit tests pass.
**Checklist**
> fix(Bytes): respect start/length of wrapped sub-arrays

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BytesTest.java
closes https://github.com/hashgraph/hedera-services/issues/13015
> chore: add more support for signatures

- pbj-core/gradle.properties
- pbj-core/pbj-compiler/src/main/antlr/com/hedera/hashgraph/protoparser/grammar/Protobuf3.g4
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Common.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/ContextualLookupHelper.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Field.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/MapField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/SingleField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/SchemaGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/json/JsonCodecGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/json/JsonCodecParseMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/json/JsonCodecWriteMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecMeasureRecordMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecWriteMethodGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/FieldType.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/JsonTools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/PbjMap.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoTestTools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoParserToolsTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java
- pbj-integration-tests/src/main/proto/everything.proto
- pbj-integration-tests/src/main/proto/map.proto
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/SampleFuzzTest.java
Introducing support for map fields in PBJ.
I apologize for the size of the PR but it would be close to impossible to break it up into reasonable pieces because all the code is deeply interconnected and needs to be updated all at once when adding a new field type.
Short summary:
1. The compiler is updated to generate Protobuf and JSON models/codecs for messages with map fields.
2. In models, the maps are present as instances of a new `PbjMap` class that implements an immutable map and provides access to a list of sorted keys to support deterministic iteration over the map entries.
3. Per the spec and the implementation of maps in protoc, they are... strange. In general, on the wire they're presented as repeated entry messages with key/value fields. However, unlike normal …
> feat: add support for maps

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoTestTools.java
> fix: avoid `BufferOverflowException` in generated JSON serialization unit tests

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/zxc-compile-pbj-code.yaml
This pull request changes the CI runner labels for improved clarity and distinction between the Dallas and Chicago clusters.
Fixes #276
> ci: update the runs-on labels for improved clarity

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Utf8Tools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/WritableSequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/ByteArrayBufferedData.java
Fix summary:
* Introduced `writeByte2()`, `writeByte3()`, and `writeByte4()` methods to `WritableSequentialData`
* By default, the methods just call `writeByte()` the right number of times
* In `ByteArrayBufferedData` the methods are implemented more efficiently than N calls to `writeByte()`
Performance:
* In `ProtobufObjectBench`, writing `Everything` to byte array output is about 12% faster than previously
Fixes: https://github.com/hashgraph/pbj/issues/284
> fix: 284: writeByte() may be improved for byte array based BufferedData

- pbj-integration-tests/build.gradle.kts
Fix summary: some classes are explicitly excluded from JMH shadow jar.
Testing:
* JMH tests work fine from command line using `java -jar build/libs/pbj-integration-tests-jmh.jar <benchmark>`
Fixes: https://github.com/hashgraph/pbj/issues/289
> fix: 289: jmhJar task fails with an error about too many entries

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/ReadableSequentialData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoParserToolsTest.java
> fix: throw on not enough bytes

- pbj-core/gradle/plugins/src/main/kotlin/com.hedera.pbj.protoc.gradle.kts
- pbj-core/pbj-grpc-helidon-config/src/main/java/com/hedera/pbj/grpc/helidon/config/PbjConfigBlueprint.java
- pbj-core/settings.gradle.kts
Upgraded Helidon, grpc and protoc versions to integrate with the latest version of Block Node
Fixes #
**Checklist**
> fix: upgraded helidon, grpc and protoc versions to work with Block Node

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/SequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/RandomAccessSequenceAdapter.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/WritableStreamingData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/test/CharBufferToWritableSequentialData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableSequentialDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableSequentialTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/SequentialDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/SequentialTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/WritableSequentialDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingDataTest.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/ParserNeverWrapsTest.java
Fix summary:
* `SequentialData.skip()` is updated to always skip the requested number of bytes
* `ReadableStreamingData.skip()` is improved to call `skip()` on the underlying input stream in a loop, till the requested number of bytes is skipped
Fixes: https://github.com/hashgraph/pbj/issues/298
> fix: 298: ReadableStreamingData.skip() doesn't check the number of actually skipped bytes 

- pbj-core/pbj-grpc-helidon/src/main/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandler.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/GreeterService.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/PbjTest.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/Pipeline.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/Pipelines.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/ServiceInterface.java
- closes #300 
- tweaks how the `PbjProtocolHandler` progresses through stream state
- uses `CLOSED` and `HALF_CLOSED_REMOTE` as specified by the [http2 spec](https://httpwg.org/specs/rfc7540.html#DATA), rather than using `HALF_CLOSED_LOCAL` for all cases of the stream ending
- modifies how the closing of protocol method calls affects method call responses
- a client completing a stream subscription request should NOT result in the responses being immediately closed. The whole idea of the subscription is that the request can be made, and the server continues to stream responses indefinitely.
> fix: Make server keep connection open after receiving ES

- pbj-core/pbj-grpc-helidon/src/main/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandler.java
Fixes #313 Fixed issue of ArrayOutOfBoundsExceptions when trying to read 4 byte integer for entity length from buffer with less than 4 bytes available.
> Fixed issue #313 of ArrayOutOfBoundsExceptions when trying to read 

- pbj-core/pbj-grpc-helidon/src/main/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandler.java
- pbj-core/pbj-grpc-helidon/src/main/java/com/hedera/pbj/grpc/helidon/RouteNotFoundHandler.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/GreeterService.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/GreeterServiceImpl.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/PbjTest.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/Pipeline.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/Pipelines.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/ServiceInterface.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/grpc/PipelinesTest.java
Change the usage from Flow.Subscriber to Pipeline
> Convert from Flow.Subscriber to Pipeline

- pbj-core/pbj-grpc-helidon/build.gradle.kts
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandlerTest.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/PbjTest.java
- pbj-core/settings.gradle.kts
Adds a new dependency when **testing**, so as to have a real implementation of metrics.
> Add support for testing with metrics

- pbj-core/pbj-grpc-helidon/src/main/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandler.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandlerTest.java
Added support for additional variations of "identity" as valid encodings. Compared with the Go gRPC server for behavior. Added tests to cover these various scenarios.
> 00330 grpc-encoding does not support all valid encodings for identity

- .github/CODEOWNERS
The purpose of this change is to add the pbj-maintainers group to the License file as defined in the CODEOWNERS file.
**Related Issue(s)**:
Fixes #332 
**Checklist**
> chore: add pbj-maintainers to License file in CODEOWNERS

- pbj-core/settings.gradle.kts
* Helidon 4.1.6 contains the fix for #329 and #403
Fixes #329 
Fixes #403
**Checklist**
> fix: helidon 4.1.6 contains the fix for #329

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/zxc-compile-pbj-code.yaml
- pbj-core/settings.gradle.kts
- pbj-integration-tests/settings.gradle.kts
- Generate code coverage reports automatically when running `check` (https://github.com/hiero-ledger/hiero-gradle-conventions/pull/74)
- Extends Yaml formatting by spotlessApply (https://github.com/hiero-ledger/hiero-gradle-conventions/issues/30)
- Automatically publishes build scans on CI so that we can remove `--scan` parameters (https://github.com/hiero-ledger/hiero-gradle-conventions/issues/32)
> build: update hiero-gradle-conventions to 0.3.0

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Common.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/ContextualLookupHelper.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Field.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/MapField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/OneOfField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/SingleField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/EnumGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/SchemaGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/json/JsonCodecGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecMeasureRecordMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecWriteMethodGenerator.java
* In some files excluded large text blocks from formatting to protect the internal structure of those blocks and keep the file readble.
* Replaced string append chains with String.formatted in many places, which helped Spotless format effectively
* Disabled spotless formatting in a few other places where the palantir format simply could not be made readable, or where it was modifying the content of text blocks.
* Adjusted a few other blocks by introducing variables and simliar small refactors to "help" the formatter produce a readable result.
> chore: Pre-fix some files that may need to be excluded from spotless.

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
As part of HIP-551, we introduce new `atomic batch` transaction. But due to circular dependency, pbj tests are failing in [services CI](https://github.com/hashgraph/hedera-services/actions/runs/12799628521/job/35686260360).
This PR adds the atomic batch transaction body in a list together with the other circular dependency fields in `TestGenerator`.
Fixes [17318](https://github.com/hashgraph/hedera-services/issues/17318)
**Checklist**
> Fix circular dependency for atomic batch

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecWriteMethodGenerator.java
Fix a NPE which is a regression of https://github.com/hashgraph/pbj/pull/366/files#diff-961773b27ac110f66f524db9b5fecaadedef721ff0c0895dc1fdf2f3a08de9d3
Stack trace:
```
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "name" is null
com.hedera.pbj.compiler.impl.Common.capitalizeFirstLetter(Common.java:58)
com.hedera.pbj.compiler.impl.generators.protobuf.CodecWriteMethodGenerator.generateFieldWriteLines(CodecWriteMethodGenerator.java:105)
com.hedera.pbj.compiler.impl.generators.protobuf.CodecWriteMethodGenerator.lambda$buildFieldWriteLines$2(CodecWriteMethodGenerator.java:55)
java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
java.base/java.util.ArrayList.forEach(ArrayList.java:1596) …
```
> Fix NPE at CodecWriteMethodGenerator

- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/NonSynchronizedByteArrayInputStream.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/integration/test/TestHashFunctions.java
* Fixed TestHashFunctions class that had trivial warnings which fail compilation due to Heiro "Warnings are errors" setting.
* Introduced in PR #109, but only became an error recently.
* Fixed a random annotation in NonSynchronizedByteArrayInputStream that was referencing the Jetbrains annotation and _between_ `byte` and `[]` in a `byte[]` return type.
* Introduced in PR #348 and not detected because pbj-integration-tests is not running in the PBJ CI suite. ([example build scan](https://scans.gradle.com/s/3cjan7qcca5ny); the gradle cache skips the entire run).
@jjohannes Could you look into why the gradle tasks are skipping everything in most CI runs?
> bug: Fix a couple errors in pbj-integration that slipped in recent PRs

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/zxc-compile-pbj-code.yaml
- pbj-integration-tests/build.gradle.kts
- pbj-integration-tests/settings.gradle.kts
- Make sure 'PBJ Integration' steps are no longer skipped (issue likely introduced in #302)
- Set Java version on CI to same version defined in 'toolchain-versions.properties' files
- Fix exist quality check issues in `pbj-integration-tests`
#302
> ci: re-enable integration tests on CI and align Java version on CI

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecDefaultInstanceMethodGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Codec.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/JsonCodec.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/CodecWrapper.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoParserToolsTest.java
This PR adds default method to the Codec's generated code. 
Fixes #404 
**Checklist**
> feat: 404 Added getDefaultValue to Codec

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/integration/test/SubTypesTest.java
- pbj-integration-tests/src/test/resources/sub_types.proto
- pbj-integration-tests/src/test/resources/sub_types_import.proto
Re-implementing fully qualified names look-up that now allows one to use partially qualified names to refer to inner and/or imported messages. This is the first part of a bigger issue described at https://github.com/hashgraph/pbj/issues/263.
Fixes #414
A new test is added to verify the new behavior.
**Checklist**
> fix: handle partially-qualified inner message names

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/FileSetWriter.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/JavaFileWriter.java
- pbj-core/pbj-compiler/src/test/java/com/hedera/pbj/compiler/impl/JavaFileWriterTest.java
Under https://github.com/hashgraph/pbj/issues/416 , we want to start generating real inner classes for inner .proto sub-types.
Currently, PBJ generators accept `File` objects pointing to main/test source directories and create files for every model on their own. In order to support generating inner classes, we need to remove this responsibility from the generators to allow them to build their generated text continuously, including all the inner classes that they may need to generate. The responsibility of creating actual physical files on disk will be with the caller of the generators.
This PR introduces utilities that will help implement the above transfer of responsibilities in the future.
Fixes #417
A new simple test is …
> feat: introduce JavaFileWriter and FileSetWriter

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/PbjCompiler.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/EnumGenerator.java
This is the very beginning of us using the new `JavaFileWriter` class. This PR simply refactors the `EnumGenerator` to use this class instead of creating a physical file on its own.
Fixes #419
All tests must continue passing. This fix is not expected to change anything in the generated code per se.
**Checklist**
> refactor: use JavaFileWriter in EnumGenerator

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/PbjCompiler.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Field.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/FileSetWriter.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/JavaFileWriter.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/MapField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/OneOfField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/SingleField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/Generator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/SchemaGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/json/JsonCodecGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecGenerator.java
In this fix we use the new `JavaFileWriter` in all the remaining message generator classes. With this fix, all the generators are no longer responsible for creating physical files for its own code that they generate - they simply emit all the generated data into the supplied writer, and the caller of the generator is responsible for calling `writeFile` on the writer to actually write a file on disk.
Please note that inner types are still written into separate files/classes. In general, as far as the actual generated code is concerned, it should be the same as before. This fix simply replaces the core mechanism of creating files on disk with using the new utilities that we've introduced recently. A switch to producing actual inner classes will happen in a separate fix in …
> refactor: use JavaFileWriter in message generators

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/PbjCompiler.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/PbjCompilerTask.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/integration/test/CompareToNegativeTest.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/integration/test/SubTypesTest.java
Introducing a feature in the `PbjCompiler` implementation that allows one to pass an optional suffix that PBJ will add to the Java package names of models that don't specify the `pbj.java_package` option explicitly. This is to support using 3rd-party protobuf models in PBJ integration test that would otherwise clash with the models generated by Google protoc compiler.
Please note that this is the core feature implementation only. A support for passing the suffix as a parameter and enabling it in the integration tests will be implemented in a separate PR under #435 .
Fixes #436 
Until #435 is implemented, there's not any easy way to test this feature in an automated fashion. However, I've tested this fix manually by overriding …
> feat: support adding Java package suffix for PBJ models

- pbj-core/pbj-compiler/src/main/antlr/com/hedera/hashgraph/protoparser/grammar/Protobuf3.g4
- pbj-integration-tests/src/main/proto/docComments.proto
Allow one to have free-standing doc comments inside oneof fields. Also test doc comments in various random locations.
Fixes #319
A new test model is added to PBJ integ tests that previously failed to compile. It's an extended version of the sample model from the description of the issue.
**Checklist**
> fix: support random doc comments in oneofs

- pbj-core/hiero-dependency-versions/build.gradle.kts
- pbj-core/settings.gradle.kts
- pbj-integration-tests/settings.gradle.kts
...and with that [update dependency-analysis-gradle-plugin to 2.16.0](https://github.com/hiero-ledger/hiero-gradle-conventions/releases/tag/v0.3.9).
The PR also introduces explicitly managing the Netty version that we use in tests (indirectly through `io.grpc.netty`). The latest Netty version ships with `module-info.class` files and is thus [no longer patched](https://github.com/hiero-ledger/hiero-gradle-conventions/releases/tag/v0.3.9).
> build: bump 'org.hiero.gradle.build' to 0.3.9

- pbj-core/pbj-grpc-helidon/build.gradle.kts
(looks like this was missed in a previous PR)
> chore: remove unnecessary line in build.gradle with FIXME comment

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoTestTools.java
- As new messages are added to protobufs, the generated test objects can get bigger and `BufferOverflowException`s return for e.g. `PublishStreamRequestTest`.
> chore: increase buffer size for JSON serialization tests

- pbj-core/pbj-grpc-helidon/build.gradle.kts
- pbj-core/settings.gradle.kts
- pbj-integration-tests/build.gradle.kts
- pbj-integration-tests/settings.gradle.kts
Update _hiero-gradle-conventions_ to _0.4.0_ and by that run tests on the _module path_.
See https://github.com/hiero-ledger/hiero-consensus-node/pull/18922 for more details on how that works.
> build: run tests on module path

- pbj-core/pbj-grpc-helidon/src/main/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandler.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandlerTest.java
Adds handing of empty requests. In those cases we receive 5 bytes, where first one is compression flag and the rest 4 are the lenght of the message that usually follows. However in case of empty request, such as [ServerStatusRequest](https://github.com/hashgraph/hedera-protobufs/blob/v0.62.1/block/block_service.proto#L837) data() method receive exactly 5 bytes, which results in not reaching onNext call on the pipeline and the client hangs, as it's waiting for the respons.
In this PR we add a condition where length is 0, so that we can continue the flow corrrectly and reset the state for the next messages. More info in the issue #483 
Fixes #483 
**Checklist**
> fix: handling empty msg in helidon plugin

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/PbjCompiler.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/PbjCompilerPlugin.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/PbjCompilerTask.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/PbjExtension.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/FileSetWriter.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/integration/test/CompareToNegativeTest.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/integration/test/SubTypesTest.java
PBJ generates test for models that mainly test the compatibility with Google protoc. Some projects may want to avoid a dependency on protoc, and hence they may not need the tests generated.
Solution: create a PBJ Gradle plugin parameter to disable tests generation.
This can be enabled (err.... disabled that is) in `build.gradle.kts` as:
```
pbj {
generateTestClasses = false
}
```
Fixes #489
All existing tests should pass. I've tried using this in the PBJ integration tests, and they obviously fail to build because there's hard-coded references to existing generated tests in, say, the FuzzTest and friends. But this exactly proves the fact that the new Gradle option works and actually prevents PBJ from generating the tests for …
> feat: support disabling tests generation

- README.md
- pbj-core/gradle/aggregation/build.gradle.kts
- pbj-core/pbj-grpc-client-helidon/README.md
- pbj-core/pbj-grpc-client-helidon/build.gradle.kts
- pbj-core/pbj-grpc-client-helidon/src/main/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcCall.java
- pbj-core/pbj-grpc-client-helidon/src/main/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcClient.java
- pbj-core/pbj-grpc-client-helidon/src/main/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcClientConfig.java
- pbj-core/pbj-grpc-client-helidon/src/main/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcClientStream.java
- pbj-core/pbj-grpc-client-helidon/src/main/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcDatagramReader.java
- pbj-core/pbj-grpc-client-helidon/src/main/java/com/hedera/pbj/grpc/client/helidon/package-info.java
- pbj-core/pbj-grpc-client-helidon/src/main/java/module-info.java
- pbj-core/pbj-grpc-client-helidon/src/test/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcDatagramReaderTest.java
- pbj-core/pbj-grpc-helidon/src/main/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandler.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/GrpcCall.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/GrpcClient.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/ServiceInterface.java
Introducing a PBJ GRPC client that only depends on the Helidon HTTP2 web client. In particular, this implementation avoids a dependency on the `io.grpc` libraries which we consider unwanted (see https://github.com/hashgraph/pbj/blob/066a5f7c1be14855e3f7793d92846eac3e828a71/pbj-core/pbj-grpc-helidon/docs/design.md?plain=1#L15-L22 ).
Fixes #518
Please see javadocs for the new classes. Integration tests for this code will be added in a future PR where we'll introduce PBJ GRPC client stubs generation.
**Checklist**
> feat: introduce PbjGrpcClient

- pbj-integration-tests/settings.gradle.kts
Update hiero-gradle-conventions to v0.4.5 to fix issue with OSSRH URL in Maven Central.
**Related Issue(s)**:
Fixes #534
> build: update hiero-gradle-conventions to v0.4.5

- pbj-core/hiero-dependency-versions/build.gradle.kts
- pbj-core/settings.gradle.kts
Upgrading dependencies to make things work and use the latest build scripts.
See https://github.com/hiero-ledger/hiero-block-node/issues/1332#issuecomment-3034619999 for more info.
Fixes #541
Builds and tests should work.
**Checklist**
> chore: upgrade org.hiero.gradle.build and byte-buddy

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Field.java
This fix increases the message size to 16M
Fixes #552 
**Checklist**
> fix: 552 Increased `Field.DEFAULT_MAX_SIZE` to 16M

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ServiceGenerator.java
- pbj-core/pbj-grpc-client-helidon/src/main/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcCall.java
- pbj-core/pbj-grpc-client-helidon/src/main/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcClient.java
- pbj-core/pbj-grpc-client-helidon/src/test/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcCallTest.java
- pbj-core/pbj-grpc-client-helidon/src/test/java/com/hedera/pbj/grpc/client/helidon/PbjGrpcClientTest.java
- pbj-core/pbj-grpc-helidon/src/main/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandler.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandlerTest.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/GrpcClient.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/ServiceInterface.java
The main goal of this PR is to improve the PBJ GRPC Client performance by establishing an HTTP2 connection only once and then re-using it by creating new HTTP2 streams to serve GRPC requests.
This fix also addresses a couple of bugs:
1. The client now properly closes the HTTP2 connection (via the `AutoClosable` interface that it now implements). Previously, it didn't, and the JVM process/system ran out of available client sockets after processing about 16K requests (back when we didn't use streams and opened a new connection for every request.) With this fix, even if we didn't switch to using streams, we'd still be able to release client sockets properly.
2. The server now properly closes the HTTP2 streams opened to serve client requests. W/o this fix and with default …
> feat: Use HTTP2 streams to improve GRPC client performance

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoArrayWriterTools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoTestTools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java
* Adding integration tests for the new `write(byte[])` feature to check the output against the existing `write(WritableSequentialData)` API
* Fixing all the bugs found along the way
Fixes #626
All tests should pass.
**Checklist**
> fix: add integ test for write(byte[]) and fix all bugs
