hashgraph/pbj

- .github/workflows/flow-deploy-release-artifact.yaml
- .idea/gradle.xml
- pbj-core/build.gradle.kts
- pbj-core/buildSrc/build.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/Utils.kt
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.aggregate-reports.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.conventions.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.maven-publish.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.repositories.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.spotless-conventions.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.spotless-java-conventions.gradle.kts
- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.spotless-kotlin-conventions.gradle.kts
- pbj-core/gradle.properties
- pbj-core/pbj-compiler/build.gradle.kts
- pbj-core/pbj-runtime/build.gradle.kts
- pbj-core/settings.gradle.kts
- pbj-integration-tests/build.gradle.kts
- pbj-integration-tests/gradle.properties
Reduces repetitive Gradle code, adds spotless support, and configures MC publishing support.
- Closes #7
> Finalize Maven Central publishing support

- .idea/gradle.xml
- .idea/misc.xml
- pbj-integration-tests/settings.gradle.kts
Signed-off-by: jasperpotts <jasperpotts@users.noreply.github.com>
Fix build issues so that IntelliJ can build directly from new clean repo
> Fixed build and intellij project so that they will build on a clean repo

- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/Common.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/Field.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/OneOfField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/SingleField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/generators/EnumGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/generators/ParserGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/generators/SchemaGenerator.java
- pbj-integration-tests/build.gradle.kts
- pbj-integration-tests/src/main/java/com/hedera/hashgraph/pbj/integration/AccountDetailsPbj.java
- pbj-integration-tests/src/main/java/com/hedera/hashgraph/pbj/integration/AccountDetailsWriter.java
Big cleanup of generated JavaDoc comments so that JavaDoc generator produces no warnings or errors.
> Big cleanup of generated JavaDoc comments

- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/generators/EnumGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/hashgraph/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/hashgraph/pbj/runtime/io/Bytes.java
- Cleaned enum java doc comments. 
- Added nice overloaded set methods to builders for lists, messages and optionals.
- Added UTF8 helper methods to Bytes.
Signed-off-by: jasperpotts <jasperpotts@users.noreply.github.com>
> Cleanup and add helper methods

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/ReadableSequentialData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableSequentialDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingDataTest.java
Added more tests and fixed a couple issues in ReadableStreamingData
> Additional test for this case.

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/RandomAccessData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BytesTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/RandomAccessDataTest.java
> Fix IOOBE when converting empty bytes to a UTF8 String

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
Work on issue #35 to add advanced hash code function to generated code.
> Add better hashCode() function for single int field objects.

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/BytesTest.java
> Added the toByteArray() API.

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/CodecGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/CodecParseMethodGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/EOFException.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingDataTest.java
> Throw a new exception when reading empty stream.

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Codec.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/WritableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/BytesTest.java
Add apropriate methods to avoid copying when storing bytes into OutputStream and MessageDigest. Also, add a method to convert a record into a Bytes object.
Fixes #
**Checklist**
> Add methods to avoid copying.

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/RandomAccessData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/BytesTest.java
Add missing writeTo and little clean up
> Added missing writeTo method and cleaned up method order and comments

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BufferedDataTest.java
> Fix BufferedData#toString method which was moving position to 0

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java
This results in about 1% speedup.
Fixes #
**Checklist**
> Convert the for-each loops to regular for loops.

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/RpcMethodDefinition.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/RpcServiceDefinition.java
> Create RpcMethodDefinition and RpcServiceDefinition

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/Utf8ToolsTest.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/ExtendedUtf8MessageWithStringTest.java
> 70 bad encoding new line char str

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BufferedDataTest.java
Closes #83. We need to use array offset consistently.
> Use array offset when needed to work with views. Add many tests.

- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.root.gradle.kts
> Add missing tasks to root project

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoConstants.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java
- pbj-core/pbj-runtime/src/test/java/tests/ProtoConstantsTest.java
Slightly improved version of the fix by Lubo: https://github.com/hashgraph/pbj/pull/88
Fixes: https://github.com/hashgraph/pbj/issues/44
> 44: Make public tag writing

- pbj-core/gradle.properties
This is a follow up related to https://github.com/hashgraph/pbj/pull/109 
Fixes # https://github.com/hashgraph/pbj/issues/95
> 095 Updated version to 0.7.7-SNAPSHOT

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecGenerator.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/protobuf/CodecParseMethodGenerator.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoConstants.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/Utf8ToolsTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/DataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableSequentialDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/ReadableTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BufferedDataTestBase.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BytesTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/ReadableStreamingDataTest.java
- pbj-core/pbj-runtime/src/test/java/tests/OneOfTest.java
Adding some unit tests which should improve the coverage for PBJ.
Fixes #125
```
pbj-core]$ gr test
...
BUILD SUCCESSFUL in 20s
```
**Checklist**
> fix 125: add unit tests

- pbj-core/gradle.properties
Updating the version of PBJ.
Fixes #https://github.com/hashgraph/hedera-services/issues/11030
Build passes.
**Checklist**
> fix 11030: update PBJ version to 0.7.13-SNAPSHOT

- pbj-core/buildSrc/src/main/kotlin/com.hedera.pbj.runtime.gradle.kts
- pbj-core/pbj-runtime/src/jmh/java/com/hedera/pbj/runtime/io/WriteBufferedDataBench.java
- pbj-core/pbj-runtime/src/jmh/java/com/hedera/pbj/runtime/io/WriteBytesBench.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/BufferedData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/RandomAccessData.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/WritableStreamingData.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/StubbedRandomAccessDataTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/stream/WritableStreamingDataTest.java
Also added JMH benchmark for reading and writing Bytes
Fixes #191
> Fix writeBytes performance, 1000x improvement. 

- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoParserToolsTest.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/MaxSizeTest.java
Adding tests for a fix introduced at https://github.com/hashgraph/pbj/pull/210
Fixes #208 
The new tests pass.
**Checklist**
> fix: 208: add tests for maxSize limit

- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/io/buffer/BytesTest.java
> fix: added return value and test for signatures

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/zxc-compile-pbj-code.yaml
- pbj-core/gradle.properties
- pbj-core/gradle/plugins/src/main/kotlin/com.hedera.pbj.conventions.gradle.kts
- pbj-core/settings.gradle.kts
- pbj-integration-tests/build.gradle.kts
- pbj-integration-tests/settings.gradle.kts
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTestResult.java
> Switch to Java 21

- pbj-core/gradle.properties
- pbj-core/gradle/plugins/build.gradle.kts
- pbj-core/gradle/plugins/src/main/kotlin/com.hedera.pbj.protoc.gradle.kts
- pbj-core/gradle/plugins/src/main/kotlin/com.hedera.pbj.runtime.gradle.kts
- pbj-core/gradle/wrapper/gradle-wrapper.properties
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/SingleField.java
- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-core/settings.gradle.kts
- Also, use proper NonNull annotation in ModelGenerator.
- Update version of spotbugs and jupiter
- Replace org.jetbrains.annotations with spotbugs annotations.
> chore: Update gradle & gradlex dependencies.

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/zxc-compile-pbj-code.yaml
Updates workflows to use latitude.sh based runners
Fixes #273
> ci: update workflows to use latitude.sh based runners

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/build.gradle.kts
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/GrpcException.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/GrpcStatus.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/Pipelines.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/ServiceInterface.java
- pbj-core/pbj-runtime/src/main/java/module-info.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/grpc/GrpcExceptionTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/grpc/GrpcStatusTest.java
- pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/grpc/PipelinesTest.java
An API which the compiler will use to generate new types of files for supporting grpc Services.
> feat: Add API for gRPC. Compiler support later.

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/zxc-compile-pbj-code.yaml
This pull request changes the following:
- Updates the runner labels for HA support.
- Closes #279
> ci: update runner labels for high availability support

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java
Fixes: https://github.com/hashgraph/pbj/issues/278
> fix: 278: Improve Bytes.equals() performance

- pbj-integration-tests/build.gradle.kts
Upgraded grpc and protobuf deps for the integration tests
Fixes #
**Checklist**
> fix: upgraded grpc and protobuf deps for the integration tests

- pbj-integration-tests/src/jmh/java/com/hedera/pbj/intergration/jmh/JsonBench.java
- pbj-integration-tests/src/jmh/java/com/hedera/pbj/intergration/jmh/ProtobufObjectBench.java
upgraded jmh usage of protobuf deps
Fixes #
**Checklist**
> fix: upgraded jmh usage of protobuf deps

- .github/workflows/flow-deploy-release-artifact.yaml
Updating gituhub action to use step-security maintained version.
Fixes #309 
**Checklist**
> ci: Updating action to use step-security maintained version.

- pbj-core/pbj-grpc-helidon/src/main/java/com/hedera/pbj/grpc/helidon/PbjProtocolHandler.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/GreeterService.java
- pbj-core/pbj-grpc-helidon/src/test/java/com/hedera/pbj/grpc/helidon/PbjTest.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/Pipeline.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/Pipelines.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/grpc/ServiceInterface.java
- duplicate of https://github.com/hashgraph/pbj/pull/305, but merging into main instead of a feature branch
- we are abandoning the feature branch and going back to normal iterative merges to `main`, since the feature branch strategy has been more confusing than helpful
> fix: Make server keep connection open after receiving ES

- .github/CODEOWNERS
Adds the PBJ-Maintainers team to the pbj repository
Fixes #317
> ci: Add PBJ-Maintainers team to repository CODEOWNERS file

- .gitignore
- pbj-integration-tests/build.gradle.kts
* Added platform folder from protobufs to build sources for integration test
* Added `.iml` files to `.gitignore`
> Fix integration test compile issue

- pbj-core/gradle.properties
- pbj-core/pbj-runtime/src/jmh/java/com/hedera/pbj/runtime/io/WritableStreamingDataBench.java
- pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/stream/WritableStreamingData.java
Fixes: https://github.com/hashgraph/pbj/issues/200
> fix: 200: Improve performance: WritableStreamingData.writeBytes(BufferedData)

- pbj-core/settings.gradle.kts
- pbj-integration-tests/settings.gradle.kts
Fixes 'publishToMavenLocal' issue
Release Notes: https://github.com/hiero-ledger/hiero-gradle-conventions/releases/tag/v0.3.1
> build: update hiero-gradle-conventions to 0.3.1

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java
- pbj-integration-tests/src/main/java/com/hedera/pbj/integration/EverythingTestData.java
- pbj-integration-tests/src/test/java/com/hedera/pbj/integration/test/ToStringTest.java
Adds code generation for toString() methods to generated model objects now that they are not Java records any more. 
Fixes #398
> Add toString method generation

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/zxc-compile-pbj-code.yaml
- pbj-core/gradle/toolchain-versions.properties
- pbj-integration-tests/gradle/toolchain-versions.properties
This is the latest JDK 21 release.
> build: bump JDK to 21.0.6

- .github/workflows/flow-deploy-release-artifact.yaml
- pbj-core/gradle/aggregation/build.gradle.kts
⚠️ Only merge after we made switched the publishing mechanism on the Maven Central side.
For more details see: https://github.com/hiero-ledger/hiero-consensus-node/pull/19567
https://github.com/hiero-ledger/hiero-consensus-node/pull/19567
> build: change publishing to use maven central publishing portal

- pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/Field.java
Misc: added a comment about not to increase the limit beyond the current value
Fixes #552 
**Checklist**
> fix: 552 Rolled back the limit to 2M size.

- pbj-integration-tests/src/jmh/java/com/hedera/pbj/integration/jmh/grpc/GrpcBench.java
Fixing a JMH bench bug discovered at https://github.com/hashgraph/pbj/pull/594#discussion_r2313493457 . The new results for the `benchServerStreaming` are just slightly changed:
```
Benchmark                       (streamCount)  (weight)   Mode  Cnt      Score     Error  Units
GrpcBench.benchServerStreaming              1     LIGHT  thrpt    5  11771.909 ± 547.431  ops/s
GrpcBench.benchServerStreaming              1    NORMAL  thrpt    5  11126.608 ± 575.820  ops/s
GrpcBench.benchServerStreaming              1     HEAVY  thrpt    5   6948.005 ± 275.980  ops/s
GrpcBench.benchServerStreaming             10     LIGHT  thrpt    5   9716.764 ± 379.403  ops/s
GrpcBench.benchServerStreaming             10    NORMAL  thrpt    5   8703.003 ± 226.194  ops/s …
```
> fix: benchServerStreaming to receive all replies

- pbj-integration-tests/src/jmh/java/com/hedera/pbj/integration/jmh/grpc/GrpcBench.java
JMH seems to run setup for both a descendant `@State` class as well as the ancestor one, resulting in starting up two servers. However, it fails to close both the servers, and this may result in timeouts. E.g. https://github.com/hashgraph/pbj/actions/runs/17742349585/job/50419237193 never finished after 6 hours.
This is likely related to the way how JMH processes `@State` classes and generates code for them, which is very complicated. So we shouldn't use inheritance for state objects in JMH.
Fixes #615
All tests should pass. The core of JMH GrpcBench hasn't changed, and it no longer prints messages from lingering servers running in the background.
**Checklist**
> fix: avoid inheritance for state classes in JMH
